# Образы берутся из 7 урока. Смотреть файл commands.md
services:
  database:
    image: 7_database
    container_name: 7_database
    environment:
      POSTGRES_DB: postgresql
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: postgresql
    volumes:
      - 9_db:/var/lib/postgresql/data
    networks:
      - 9_net

  backend:
    image: 7_back
    container_name: 7_back
    environment:
      HOST: database
      PORT: 5432
      DB: postgresql
      DB_USERNAME: postgresql
      DB_PASSWORD: postgresql
    depends_on:
      - database
    networks:
      - 9_net

  frontend:
    image: 7_nginx
    container_name: 7_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    # если не указывать сеть, то
    # - контейнер не попадет в сеть 9_net(похоже, что не попадет вообще ни в какую сеть) и UI не будет работать
    # - будет создана дефолтная сеть с названием <project>_default - 9_docker_compose_default
    networks:
      - 9_net
    # без указания зависимости backend может подняться позже. Но когда поднимется 7_nginx он вызовет проверку
    # бэкенда(nginx/nginx.conf:28) и упадет с ошибкой
    depends_on:
      - backend

volumes:
  9_db:
    name: 9_db
networks:
  9_net:
    name: 9_net
